accumulate_grad_batches: 1
adam_epsilon: 1.0e-08
amp_level: O1
batch_size: 32
default_root_dir: /minio-input/alchemy/flmingo/
deterministic: 0
distributed_backend: ddp
fast_dev_run: 0
gpus: 2
is_same_smiles: 0
learning_rate: 3.0e-05
learning_rate_scheduler: cosine_annealing_warm_restarts
limit_val_batches: 1.0
masked_lm: 1
max_epochs: 100
max_position_embeddings: 512
max_seq_length: 128
min_epochs: 5
named_descriptor_set: all
num_nodes: 1
num_physchem_properties: 200
num_workers: 16
permute: 1
precision: 32
progress_bar_refresh_rate: 25
redis_db: 0
redis_host: flmingo-redis.dev.vlt.beno.ai
redis_password: ''
redis_port: 6379
resume_from_checkpoint: /minio-input/alchemy/flmingo/lightning_logs/version_54/checkpoints/last.ckpt
test_file: null
tiny: false
tpu_cores: null
train_file: /minio-input/research/evochem/guacamol/data/guacamol_v1_train.smiles
use_offset: 1
use_redis: 0
val_check_interval: 0.25
valid_file: /minio-input/research/evochem/guacamol/data/guacamol_v1_valid.smiles
vocab_size: 42
warmup_proportion: 0.1
weight_decay: 0.0
